### PR TITLE
Format shell commands as code in README.

### PR DESCRIPTION
**Pull request by iphydf**

### CODE REVIEW

**Comment by Diadlo** [comment]
Links on the bottom of the file can be replaced on text. I.e. in the middle of file use [text], and on the bottom (may be, after 2 lines) write [text]: https://<link>

See qTox [MAINTAINING.md](https://raw.githubusercontent.com/qTox/qTox/master/MAINTAINING.md) and [INSTALL.md](https://raw.githubusercontent.com/qTox/qTox/master/INSTALL.md)

**Comment by iphydf** [comment]
@Diadlo so, I did as you said, but I don't see how it helps. It's not auto-linked, and `[1]` is a more common way to do footnotes.

**Comment by Diadlo** [comment]
@iphydf Remove `- ` before link on the bottom. And they should be linked automatically

**Comment by iphydf** [comment]
Ah, neat. Thanks, that worked.

**Pull request merged**
